### ISSUE TITLE
404 on (master) README.md - " Links Úteis "

### ISSUE THREAD

**Issue by Gustavobelfort** [Abduzidos/LearnGit#3]
O item retorna 404 ao tentar linkar com a página do codecademy

```
Links Úteis
- Lista de comandos
```

**Comment by OtacilioN** [comment]
Opa, valeu @Gustavobelfort , vi agora que ficou duplicado, vou subir um hotfix agora mesmo!

**Comment by OtacilioN** [comment]
Fixed!
